services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://host.docker.internal:9092
    ports:
      - "9092:9092"   # host -> container kafka port
      - "9644:9644"   # admin api
    networks:
      - rp-net

  console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKERS=redpanda:9092
    ports:
      - "8080:8080"
    networks:
      - rp-net

networks:
  rp-net:
    driver: bridge
